name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: .github/scripts/gradlew_subprojects.sh test
      - name: Zip reports
        run: zip -r reports.zip . -i '**/reports/*.xml' '**/reports/*.hml'
      - name: Upload reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports.zip

  apk:
    name: Build Artifacts
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build artifacts
        run: .github/scripts/gradlew_subprojects.sh assembleDebug
      - name: Zip artifacts
        run: zip -r artifacts.zip . -i '**/build/*.apk' '**/build/*.aab' '**/build/*.aar' '**/build/*.so'
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts.zip
