name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: .github/scripts/unit_test.sh
      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: "**/reports/*"

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: .github/scripts/build_apk.sh
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: "**/*.apk"
